/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as FolderFolderIdRouteImport } from './routes/folder.$folderId'
import { Route as DocDocIdIndexRouteImport } from './routes/doc.$docId.index'
import { Route as DocDocIdCameraRouteImport } from './routes/doc.$docId.camera'
import { Route as DocDocIdReviewRouteImport } from './routes/doc.$docId.review'
import { Route as DocDocIdPagePageIdIndexRouteImport } from './routes/doc.$docId.page.$pageId.index'
import { Route as DocDocIdPagePageIdEditRouteImport } from './routes/doc.$docId.page.$pageId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderFolderIdRoute = FolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDocIdIndexRoute = DocDocIdIndexRouteImport.update({
  id: '/doc/$docId/',
  path: '/doc/$docId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDocIdCameraRoute = DocDocIdCameraRouteImport.update({
  id: '/doc/$docId/camera',
  path: '/doc/$docId/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDocIdReviewRoute = DocDocIdReviewRouteImport.update({
  id: '/doc/$docId/review',
  path: '/doc/$docId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDocIdPagePageIdIndexRoute = DocDocIdPagePageIdIndexRouteImport.update({
  id: '/doc/$docId/page/$pageId/',
  path: '/doc/$docId/page/$pageId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDocIdPagePageIdEditRoute = DocDocIdPagePageIdEditRouteImport.update({
  id: '/doc/$docId/page/$pageId/edit',
  path: '/doc/$docId/page/$pageId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/doc/$docId/camera': typeof DocDocIdCameraRoute
  '/doc/$docId/review': typeof DocDocIdReviewRoute
  '/doc/$docId/': typeof DocDocIdIndexRoute
  '/doc/$docId/page/$pageId/edit': typeof DocDocIdPagePageIdEditRoute
  '/doc/$docId/page/$pageId/': typeof DocDocIdPagePageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/doc/$docId/camera': typeof DocDocIdCameraRoute
  '/doc/$docId/review': typeof DocDocIdReviewRoute
  '/doc/$docId': typeof DocDocIdIndexRoute
  '/doc/$docId/page/$pageId/edit': typeof DocDocIdPagePageIdEditRoute
  '/doc/$docId/page/$pageId': typeof DocDocIdPagePageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/folder/$folderId': typeof FolderFolderIdRoute
  '/doc/$docId/camera': typeof DocDocIdCameraRoute
  '/doc/$docId/review': typeof DocDocIdReviewRoute
  '/doc/$docId/': typeof DocDocIdIndexRoute
  '/doc/$docId/page/$pageId/edit': typeof DocDocIdPagePageIdEditRoute
  '/doc/$docId/page/$pageId/': typeof DocDocIdPagePageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/settings'
    | '/trash'
    | '/folder/$folderId'
    | '/doc/$docId/camera'
    | '/doc/$docId/review'
    | '/doc/$docId/'
    | '/doc/$docId/page/$pageId/edit'
    | '/doc/$docId/page/$pageId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/settings'
    | '/trash'
    | '/folder/$folderId'
    | '/doc/$docId/camera'
    | '/doc/$docId/review'
    | '/doc/$docId'
    | '/doc/$docId/page/$pageId/edit'
    | '/doc/$docId/page/$pageId'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/settings'
    | '/trash'
    | '/folder/$folderId'
    | '/doc/$docId/camera'
    | '/doc/$docId/review'
    | '/doc/$docId/'
    | '/doc/$docId/page/$pageId/edit'
    | '/doc/$docId/page/$pageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TrashRoute: typeof TrashRoute
  FolderFolderIdRoute: typeof FolderFolderIdRoute
  DocDocIdCameraRoute: typeof DocDocIdCameraRoute
  DocDocIdReviewRoute: typeof DocDocIdReviewRoute
  DocDocIdIndexRoute: typeof DocDocIdIndexRoute
  DocDocIdPagePageIdEditRoute: typeof DocDocIdPagePageIdEditRoute
  DocDocIdPagePageIdIndexRoute: typeof DocDocIdPagePageIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder/$folderId': {
      id: '/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof FolderFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$docId/': {
      id: '/doc/$docId/'
      path: '/doc/$docId'
      fullPath: '/doc/$docId/'
      preLoaderRoute: typeof DocDocIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$docId/camera': {
      id: '/doc/$docId/camera'
      path: '/doc/$docId/camera'
      fullPath: '/doc/$docId/camera'
      preLoaderRoute: typeof DocDocIdCameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$docId/review': {
      id: '/doc/$docId/review'
      path: '/doc/$docId/review'
      fullPath: '/doc/$docId/review'
      preLoaderRoute: typeof DocDocIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$docId/page/$pageId/': {
      id: '/doc/$docId/page/$pageId/'
      path: '/doc/$docId/page/$pageId'
      fullPath: '/doc/$docId/page/$pageId/'
      preLoaderRoute: typeof DocDocIdPagePageIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$docId/page/$pageId/edit': {
      id: '/doc/$docId/page/$pageId/edit'
      path: '/doc/$docId/page/$pageId/edit'
      fullPath: '/doc/$docId/page/$pageId/edit'
      preLoaderRoute: typeof DocDocIdPagePageIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TrashRoute: TrashRoute,
  FolderFolderIdRoute: FolderFolderIdRoute,
  DocDocIdCameraRoute: DocDocIdCameraRoute,
  DocDocIdReviewRoute: DocDocIdReviewRoute,
  DocDocIdIndexRoute: DocDocIdIndexRoute,
  DocDocIdPagePageIdEditRoute: DocDocIdPagePageIdEditRoute,
  DocDocIdPagePageIdIndexRoute: DocDocIdPagePageIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
